version: "3"

vars:
  IMAGE_NAME: go-idasen-desk
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -ldflags "-X github.com/AlejandroHerr/go-idasen-desk/version.Version={{.VERSION}} -X github.com/AlejandroHerr/go-idasen-desk/version.Commit={{.COMMIT}} -X github.com/AlejandroHerr/go-idasen-desk/version.BuildTime={{.BUILD_TIME}}"

tasks:
  run/scanner:
    cmds:
      - go run -v ./cmd/scanner/main.go
  build/scanner:
    desc: Build scanner application
    cmds:
      - echo "Building scanner {{.VERSION}} ({{.COMMIT}})"
      - go build {{.LDFLAGS}} -o bin/scanner ./cmd/scanner
    sources:
      - cmd/scanner/**/*.go
      - version/*.go
    generates:
      - bin/scanner
  lint:
    desc: Run linters
    cmds:
      - golangci-lint run --timeout 5m
  lint/fix:
    desc: Run linters and fix issues
    cmds:
      - golangci-lint run --fix --timeout 5m
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
  docker/scanner:
    desc: Build scanner Docker image
    cmds:
      - docker build
        --build-arg VERSION={{.VERSION}}
        --build-arg COMMIT={{.COMMIT}}
        --build-arg BUILD_TIME={{.BUILD_TIME}}
        -t {{.IMAGE_NAME}}-scanner:{{.VERSION}}
        -f Dockerfile.scanner .
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
