name: Go Linting

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.24"
      golangci-version:
        required: false
        type: string
        default: "v2"
jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ inputs.golangci-version }}
