name: Go Linting

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      golangci-version:
        required: true
        type: string
jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ inputs.golangci-version }}
