name: Build and Publish Applications

on:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "apps=$(cat apps.json | jq -c .apps)" >> $GITHUB_OUTPUT
  build_app:
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/_build.yaml
    strategy:
      matrix:
        app: ${{ fromJson(needs.prepare.outputs.apps) }}
    with:
      app: ${{ matrix.app }}
