name: Build and Publish Applications

on:
  push:
    tags:
      - "v*"

jobs:
  build_app:
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/_build.yaml
    strategy:
      matrix:
        app: [scanner]
    with:
      app: ${{ matrix.app }}
