name: Build and Publichs Applications

on:
  push:
    tags:
      - v*

jobs:
  build_app:
    uses: ./.github/workflows/_build.yaml
    strategy:
      matrix:
        app: [scanner]
    with:
      app: ${{ matrix.app }}
