name: Build and Publichs Applications

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [scanner]
    steps:
      - name: Run for ${{ matrix.app }}
        uses: ./.github/workflows/_build.yaml
        with:
          app: ${{ matrix.app }}
          version: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          build_time: ${{ steps.version.outputs.build_time }}
